language: 'php'

php:
  - '7.1'

cache:
  directories:
    - "$HOME/.cache/composer/files"

before_install:
  - composer self-update

install:
  - composer update --prefer-source

script: vendor/bin/phpunit --coverage-text=php://stdout --colors=never